//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public abstract class AbstractBehaviour : MonoBehaviour
{
	public Mind owner;
	public int priority;

	public abstract void Act();
	public abstract bool Think();

	public void Initialize(Mind owner)
	{
		this.owner = owner;
	}

}

