//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
		
public class Body : MonoBehaviour
{
	public float m_velocity;
	public float m_shootforce;
  public float m_actionray = 10;
	public float m_minactionray = 2;
	public float m_ballaction = 1;
	public float m_shootdistance = 5;
	public Vector3 m_initpos;

	public void Awake()
	{
		m_initpos = transform.position;
	}

	public void Move(Vector3 direction)
	{
		if (direction != Vector3.zero)
		{
			float stepX = direction.x * Time.deltaTime * m_velocity;
			float stepY = direction.y * Time.deltaTime * m_velocity;
			
			transform.position = new Vector3(transform.position.x + stepX, transform.position.y + stepY, 0);
		}
	}

	public void Update()
	{

	}
}

