//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

public enum Team
{
	Blue,
	Red
}

public class Mind : MonoBehaviour
{
	public float visionRadius = 100f;

	public GameObject behavioursHolder;
	public GameObject ball;

	public List<Body> enemies;
	public List<Body> allies;
	public Body body;
	public Body target;

	public List<AbstractBehaviour> behaviours;
	public AbstractBehaviour lastBehaviours;

	public Team myTeam;
	
	void Start()
	{
		ball = GameObject.Find("Bola");
		behaviours = new List<AbstractBehaviour>();

		foreach (AbstractBehaviour ab in behavioursHolder.GetComponents<AbstractBehaviour>())
		{
			ab.Initialize(this);
			behaviours.Add(ab);
		}

		behaviours.Sort((x, y) => x.priority.CompareTo(y.priority));
	}

	void Update()
	{
		enemies.Clear();
		allies.Clear();

		Collider[] cols = Physics.OverlapSphere(transform.position, visionRadius);

		foreach (Collider c in cols)
		{
			Body body = c.gameObject.GetComponent<Body>();

			if (body != null && body.gameObject != this.gameObject)
			{
				if (myTeam == body.GetComponent<Mind>().myTeam)
					allies.Add(body);
				else
					enemies.Add(body);
			}
		}

		for (int i = 0; i < behaviours.Count; i++)
		{
			if (behaviours[i].Think())
			{
				lastBehaviours = behaviours[i];
			}
		}

		lastBehaviours.Act();
	}
}