//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
		
public class Bullet : MonoBehaviour
{
	public float speed;
	public float damage;
	public float maxDistance;
	public Vector3 direction;

	public Body owner;

	public void Shoot(Body owner, Vector3 direction)
	{
		this.owner = owner;
		this.direction = direction;
	}

	//TODO Collision
	public void OnTriggerEnter(Collider col)
	{
		Debug.Log ("asofdas");

		Body b = col.gameObject.GetComponent<Body>();

		if (b != null && b != owner)
		{
			b.TakeDamage(this.damage);
		}

		Destroy (this);
	}

	void Update()
	{
		if (direction != Vector3.zero)
		{
			float stepX = direction.x * Time.deltaTime * speed;
			float stepY = direction.y * Time.deltaTime * speed;
			
			transform.position = new Vector3(transform.position.x + stepX, transform.position.y + stepY, 0);
		}
	}
}

